spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/challenges?serverTimezone=Asia/Seoul
    username: ironjin
    password: didcjf12
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.naver.com
    port: 465
    username: gra1259
    password: dfasdf
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true


logging.level:
  org.hibernate.SQL: debug